# Generated by Django 3.1.2 on 2020-10-29 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='administrador',
            new_name='ModelAdministrador',
        ),
    ]
