# Generated by Django 3.1.2 on 2020-10-31 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0002_auto_20201029_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeladministrador',
            name='answer_question',
            field=models.CharField(default='Respuesta', max_length=100, verbose_name='Respuesta Seguridad'),
        ),
        migrations.AlterField(
            model_name='modeladministrador',
            name='security_question',
            field=models.CharField(choices=[('¿Cual es tu banda favorita?', '¿Cual es tu banda favorita?'), ('¿Objeto mas valioso para usted?', '¿Objeto mas valioso para usted?'), ('¿Nombre de su perro?', '¿Nombre de su perro?')], default='Elija pregunta', max_length=50, verbose_name='Pregunta Seguridad'),
        ),
    ]
