# Generated by Django 3.1.2 on 2020-11-04 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0003_auto_20201031_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre Producto')),
                ('short_description', models.CharField(max_length=100, verbose_name='Descripcion Corta')),
                ('description', models.CharField(max_length=200, verbose_name='Descripcion')),
                ('mg', models.IntegerField()),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('price', models.CharField(max_length=50, verbose_name='precio')),
                ('stock', models.BooleanField(verbose_name='Disponibilidad')),
            ],
        ),
        migrations.AlterField(
            model_name='modeladministrador',
            name='security_question',
            field=models.CharField(max_length=50, verbose_name='Pregunta Seguridad'),
        ),
    ]
